public class OnboardingStages {
    public final static String OPS_CALL_NEEDED = 'Ops Call Needed';
    public final static String OPS_CALL_BOOKED = 'Ops Call Booked';
    public final static String OPS_CALL_HELD = 'Ops Call Held';
    public final static String TRAINING_SCHEDULED = 'Training Scheduled';
    public final static String NEEDS_SETUP = 'Needs Setup';
    public final static String MATERIALS_SHIPPED = 'Materials Shipped';
    public final static String SETUP_COMPLETE = 'Setup Complete';
    public final static String TRAINING_PENDING = 'Training Pending';
}