public class SalesStages  {
    public final static String DISCOVERY_CALL_SCHEDULED = 'Discovery Call Scheduled';
    public final static String DEMO_MISSED = 'Demo Missed';
    public final static String CONTRACT_SENT = 'Contract Sent';
    public final static String CONFIRMING = 'Confirming';
    public final static String NEEDS_SETUP = 'Needs Setup';
    public final static String CONTRACT_SIGNED = 'Contract Signed';
    public final static String DISCOVERY_VALUE_CONNECTION = 'Discovery / Value Connection';
}